### ISSUE TITLE
Exists problem on debugging using device

### ISSUE THREAD

**Issue by startsev** [ms88privat/react-native-video-gstreamer#1]
When trying to launch on device 4.4 app crashed every time
When started with genymotion not raised any error

**Comment by ms88privat** [comment]
@startsev genymotion (or any other emulator) will not work because the jni binaries are only for the arm and armv7 architecture compiled (=> most Android Phones) and not for x86 (computer).

Could you please check all of the steps in the install guide again? Could you debug the App via "adp logcat" in Android Studio and post the result here? Thanks a lot!

**Comment by startsev** [comment]
@ms88privat Yeah, sure
 I did all that described in install manual, but got on device from adb logcat

```
D/dalvikvm( 1540): Trying to load lib /data/app-lib/com.videotest-1/libreactnativejni.so 0x43a1da30
I/WifiHW  (  533): CMD: IFNAME=wlan0 SIGNAL_POLL
D/wpa_supplicant(22009): RX ctrl_iface - hexdump(len=11): 53 49 47 4e 41 4c 5f 50 4f 4c 4c
D/wpa_supplicant(22009): wlan0: Control interface command 'SIGNAL_POLL'
D/wpa_supplicant(22009): nl80211: survey data missing!
I/WifiHW  (  533): REPLY: RSSI=-64
I/WifiHW  (  533): REPLY: LINKSPEED=26
I/WifiHW  (  533): REPLY: NOISE=9999
I/WifiHW  (  533): REPLY: FREQUENCY=2462
D/houdini ( 1540): [1540] Loading library(version: 4.0.8.45720 RELEASE)... successfully.
D/houdini ( 1540): [1540] Unsupported feature (ID:0x10600cae).
D/houdini ( 1540): [1540] Open Native Library /data/app-lib/com.videotest-1/libreactnativejni.so failed.
E/dalvikvm( 1540): dlopen("/data/app-lib/com.videotest-1/libreactnativejni.so") failed: dlopen failed: "/data/app-lib/com.videotest-1/libreactnativejni.so" has unexpected e_machine: 40
W/dalvikvm( 1540): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/facebook/react/bridge/JSCJavaScriptExecutor;
D/AndroidRuntime( 1540): Shutting down VM
W/dalvikvm( 1540): threadid=1: thread exiting with uncaught exception (group=0x430ef140)
E/AndroidRuntime( 1540): FATAL EXCEPTION: main
E/AndroidRuntime( 1540): Process: com.videotest, PID: 1540
E/AndroidRuntime( 1540): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app-lib/com.videotest-1/libreactnativejni.so" has unexpected e_machine: 40
E/AndroidRuntime( 1540):    at java.lang.Runtime.load(Runtime.java:333)
E/AndroidRuntime( 1540):    at java.lang.System.load(System.java:512)
E/AndroidRuntime( 1540):    at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
E/AndroidRuntime( 1540):    at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:209)
E/AndroidRuntime( 1540):    at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:178)
E/AndroidRuntime( 1540):    at com.facebook.react.bridge.JSCJavaScriptExecutor.<clinit>(JSCJavaScriptExecutor.java:19)
E/AndroidRuntime( 1540):    at com.facebook.react.ReactInstanceManager.onJSBundleLoadedFromServer(ReactInstanceManager.java:310)
E/AndroidRuntime( 1540):    at com.facebook.react.ReactInstanceManager.initializeReactContext(ReactInstanceManager.java:321)
E/AndroidRuntime( 1540):    at com.facebook.react.ReactInstanceManager.attachMeasuredRootView(ReactInstanceManager.java:265)
E/AndroidRuntime( 1540):    at com.facebook.react.ReactRootView$1.run(ReactRootView.java:105)
E/AndroidRuntime( 1540):    at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 1540):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 1540):    at android.os.Looper.loop(Looper.java:149)
E/AndroidRuntime( 1540):    at android.app.ActivityThread.main(ActivityThread.java:5268)
E/AndroidRuntime( 1540):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1540):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 1540):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime( 1540):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
E/AndroidRuntime( 1540):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  533):   Force finishing activity com.videotest/.MainActivity
I/WindowManager(  533): Screenshot max retries 4 of Token{22401848 ActivityRecord{221eae90 u0 com.videotest/.MainActivity id=0 t883 f}} appWin=Window{21e2fb10 u0 id=0 com.videotest/com.videotest.MainActivity} drawState=1
```

and the problem is that can't be found libreactnativejni.so , device - 4.4 asus zenfone 5

**Comment by ms88privat** [comment]
@startsev I'm not sure about this one. I can not help you here at the moment. There is a completely new version planned anyways... but could take 1-2 months

**Comment by lyahdav** [comment]
Pretty sure this issue is same as https://github.com/facebook/react-native/issues/5773. You have to include x86 in your `abiFilters` in `build.gradle` file.
